# Generated by Django 3.2.4 on 2021-07-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_consumed_consume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='satFats',
        ),
    ]
